// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcx_lGUwWtpyjWUqE58Je2fErCPIAQpdQ',
    appId: '1:892062208639:web:e10e69cef2697881b9254a',
    messagingSenderId: '892062208639',
    projectId: 'sportbike-id',
    authDomain: 'sportbike-id.firebaseapp.com',
    storageBucket: 'sportbike-id.firebasestorage.app',
    measurementId: 'G-FFMYGX17MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIOODdY7xbNpGajAzD0ZElcZK2VUV1HHs',
    appId: '1:892062208639:android:20ab13cac2d4a46fb9254a',
    messagingSenderId: '892062208639',
    projectId: 'sportbike-id',
    storageBucket: 'sportbike-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbTkoE14oaEysmV7xjrDKD58NMw1ImDcg',
    appId: '1:892062208639:ios:e0fe596088601dacb9254a',
    messagingSenderId: '892062208639',
    projectId: 'sportbike-id',
    storageBucket: 'sportbike-id.firebasestorage.app',
    iosBundleId: 'com.example.sportbikeId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbTkoE14oaEysmV7xjrDKD58NMw1ImDcg',
    appId: '1:892062208639:ios:e0fe596088601dacb9254a',
    messagingSenderId: '892062208639',
    projectId: 'sportbike-id',
    storageBucket: 'sportbike-id.firebasestorage.app',
    iosBundleId: 'com.example.sportbikeId',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcx_lGUwWtpyjWUqE58Je2fErCPIAQpdQ',
    appId: '1:892062208639:web:f9fda23b01dd6125b9254a',
    messagingSenderId: '892062208639',
    projectId: 'sportbike-id',
    authDomain: 'sportbike-id.firebaseapp.com',
    storageBucket: 'sportbike-id.firebasestorage.app',
    measurementId: 'G-4Y5SJG0L9V',
  );
}
